Khawla.Web/ViewModels/CheckoutViewModel.cs
using Khawla.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Khawla.Web.ViewModels
{
    public class CheckoutViewModel
    {
        public List<Product> CartProducts { get; set; }
        public List<int> CartProductIDs { get; set; }

        public KhawlaUser User { get; set; }
    }
}

Khawla.Web/ViewModels/ShopViewModel.cs
using Khawla.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Khawla.Web.ViewModels
{
    public class ShopViewModel
    {
        public List<Product> Products { get; set; }
        public List<Product> LatestProduct { get; set; }
        public int MaximumPrice { get; set; }
        public int MinimumPrice { get; set; }
        public List<Category> FeaturedCategories { get; set; }
        public List<Category> AllCategory { get; set; }
        public int? SortBy { get; set; }
        public int? CategoryID { get; set; }
        public int? SubCategoryID { get; set; }
        public Pager Pager { get; set; }
        public string SearchTerm { get; set; }
        public int totalCount { get; set; }
    }
    public class FilterProductsViewModel
    {
        public List<Product> Products { get; set; }
        public Pager Pager { get; set; }
        public int? SortBy { get; set; }
        public int? CategoryID { get; set; }
        public int? SubCategoryID { get; set; }
        public string SearchTerm { get; set; }
    }
}

Khawla.Web/Controllers/ProductsController.cs
using Khawla.Entities;
using Khawla.Service;
using Khawla.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Khawla.Web.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult ProductList(int? categoryId, string search, int? pageNo )
        {
            var pageSize = 3;
            pageNo = pageNo ?? 1;

            ProductListingViewModel model = new ProductListingViewModel();
            //model.PageNo= pageNo ?? 1;
            model.CategoryId = categoryId;
            model.SearchTerm = search;
            
            model.AllProduct = ProductsService.Instance.FilterProduct(categoryId, search, pageNo.Value, pageSize);
            model.AllCategory = CategoriesService.Instance.allCategory();
            var totalProducts = ProductsService.Instance.GetProductCount(categoryId, search);

            model.Pager = new Pager(totalProducts, pageNo, pageSize);

            return PartialView(model);
        }

        public ActionResult Create()
        {
            ProductsCreateViewModel model = new ProductsCreateViewModel();
            model.Categories = CategoriesService.Instance.allCategory();
            model.SubCategories = SubCategoriesService.Instance.allSubCategory();
            return PartialView(model);
        }
        [HttpPost]
        public JsonResult Create(ProductsCreateViewModel model)
        {
            JsonResult result = new JsonResult();
            if (ModelState.IsValid)
            {
                var newProduct = new Product();

                newProduct.Name = model.Name;
                newProduct.Description = model.Description;
                newProduct.Summery = model.Summery;
                newProduct.Price = model.Price;
                newProduct.Quantity = model.Quantity;
                newProduct.CategoryId = model.CategoryId;
                newProduct.SubCategoryId = model.SubCategoryId;

                if (!string.IsNullOrEmpty(model.ProductPictures))
                {
                    var pictureId = model.ProductPictures
                        .Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                        .Select(int.Parse).ToList();
                    newProduct.ProductPictures = new List<ProductPicture>();
                    newProduct.ProductPictures.AddRange(pictureId.Select(s => new ProductPicture()
                    { ProductId = newProduct.ID, PictureId = s }).ToList());
                }
                ProductsService.Instance.SaveProduct(newProduct);

                result.Data = new { success = true };
            }
            else
            {
                result.Data = new { success = false, message = "Invalid Inputs" };
            }
            return result;
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            ProductsCreateViewModel model = new ProductsCreateViewModel();

            model.Product = ProductsService.Instance.GetProductById(Id);
            model.Categories = CategoriesService.Instance.allCategory();


            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(ProductsCreateViewModel model)
        {
            
            var Product = ProductsService.Instance.GetProductById(model.Id);
            Product.Name = model.Name;
            Product.Summery = model.Summery;
            Product.Description = model.Description;
            Product.Price = model.Price;
            Product.Quantity = model.Quantity;
            Product.CategoryId = model.CategoryId;


            if (!string.IsNullOrEmpty(model.ProductPictures))
            {
                var pictureIds = model.ProductPictures.Split(',').Select(int.Parse);
                Product.ProductPictures = new List<ProductPicture>();
                Product.ProductPictures.AddRange(pictureIds.Select(x => new ProductPicture() { ProductId = Product.ID, PictureId = x }).ToList());

            }



            ProductsService.Instance.UpdateProduct(Product);

            return RedirectToAction("ProductList");
        }

        [HttpGet]
        public ActionResult Details(int Id)
        {
            ProductDetalisViewModel model = new ProductDetalisViewModel();

            model.Product = ProductsService.Instance.GetProductById(Id);
            


            return View(model);
        }
        [HttpPost]
        public ActionResult Delete(int Id)
        {

            ProductsService.Instance.Deleteproduct(Id);
            return RedirectToAction("ProductList");
        }

    }
}

Khawla.Web/Controllers/ShopController.cs
using Khawla.Service;
using Khawla.Web.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Khawla.Web.Controllers
{
    public class ShopController : Controller
    {

        private KhawlaSignInManager _signInManager;
        private KhawlaUserManager _userManager;

        public KhawlaSignInManager SignInManager
        {
            get { return _signInManager ?? HttpContext.GetOwinContext().Get<KhawlaSignInManager>(); }
            private set { _signInManager = value; }

        }
        public KhawlaUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<KhawlaUserManager>(); }
            private set { _userManager = value; }
        }


        // GET: Shop
        public ActionResult Index(string searchTerm, int? maximumPrice, int? minimumPrice, int? categoryID, int? subcategoryID, int? sortBy, int? pageNo)
        {
            var pageSize = 4;
            pageNo = pageNo ?? 1;

            ShopViewModel model = new ShopViewModel();

            model.LatestProduct = ProductsService.Instance.GetLatestProduct(6);

            model.SearchTerm = searchTerm;
            model.FeaturedCategories = CategoriesService.Instance.GetFeatureCategories();
            model.AllCategory= CategoriesService.Instance.allCategory();
            model.MaximumPrice = ProductsService.Instance.GetMaximumPrice();
            model.MinimumPrice = ProductsService.Instance.GetMinimumPrice();
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.CategoryID = categoryID;
            model.SubCategoryID = subcategoryID;
            model.SortBy = sortBy;
            model.Products = ProductsService.Instance.SearchProducts(searchTerm, maximumPrice, minimumPrice, categoryID, subcategoryID, sortBy, pageNo.Value, pageSize);
            
            model.totalCount = ProductsService.Instance.SearchProductsCount(searchTerm, maximumPrice, minimumPrice, categoryID, subcategoryID, sortBy);
            model.Pager = new Pager(model.totalCount, pageNo, pageSize);

            return View(model);
        }
        public ActionResult FilterProducts(string searchTerm, int? maximumPrice, int? minimumPrice, int? categoryID,int? subcategoryID, int? sortBy, int? pageNo)
        {
            var pageSize = 4;
            pageNo = pageNo ?? 1;

            FilterProductsViewModel model = new FilterProductsViewModel();

            model.SearchTerm = searchTerm;
            model.CategoryID = categoryID;
            model.SubCategoryID = subcategoryID;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.SortBy = sortBy;
            int totalCount = ProductsService.Instance.SearchProductsCount(searchTerm, maximumPrice, minimumPrice, categoryID,subcategoryID, sortBy);
            model.Products = ProductsService.Instance.SearchProducts(searchTerm, maximumPrice, minimumPrice, categoryID, subcategoryID, sortBy, pageNo.Value, pageSize);

            model.Pager = new Pager(totalCount, pageNo, pageSize);

            return PartialView(model);
        }
       
        public ActionResult ShopingCart()
        {
            CheckoutViewModel model = new CheckoutViewModel();

            var CardProductsCookie = Request.Cookies["CartProducts"];
            if(CardProductsCookie!=null&& !string.IsNullOrEmpty(CardProductsCookie.Value))
            {
                model.CartProductIDs = CardProductsCookie.Value
                    .Split('-').Select(x => int.Parse(x)).ToList();
                model.CartProducts = ProductsService.Instance.GetProducts(model.CartProductIDs);

               
            }
            return View(model);
        }
        [Authorize]
        public ActionResult CheckOut()
        {
            CheckoutViewModel model = new CheckoutViewModel();

            var CardProductsCookie = Request.Cookies["CartProducts"];
            if (CardProductsCookie != null && !string.IsNullOrEmpty(CardProductsCookie.Value))
            {
                model.CartProductIDs = CardProductsCookie.Value
                    .Split('-').Select(x => int.Parse(x)).ToList();
                model.CartProducts = ProductsService.Instance.GetProducts(model.CartProductIDs);

                model.User = UserManager.FindById(User.Identity.GetUserId());
            }
            return View(model);
        }
    }
}

Khawla.Web/Controllers/WidgetsController.cs
using Khawla.Entities;
using Khawla.Service;
using Khawla.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Khawla.Web.Controllers
{
    public class WidgetsController : Controller
    {
        // GET: Widgets
        public ActionResult Products(bool isFeatured, bool isLatestProduct, bool topRated, bool topReview, int? CategoryID = 0)
        {

            ProductsWidgetViewModel model = new ProductsWidgetViewModel();
            model.Isfeatured = isFeatured;
            model.IsLatestProduct = isLatestProduct;
            model.toprated = topRated;
            model.topreview = topReview;
            if (isFeatured)
            {
                model.AllWidgetProduct = ProductsService.Instance.GetFeatureProduct();
            }
            else if (isLatestProduct)
            {
                model.AllWidgetProduct = ProductsService.Instance.GetLatestProduct(12);
            }
            else if (topRated)
            {
                model.AllWidgetProduct = ProductsService.Instance.GetLatestProduct(12);
            }
            else if (topReview)
            {
                model.AllWidgetProduct = ProductsService.Instance.GetLatestProduct(12);
            }
            else if (CategoryID.HasValue && CategoryID.Value > 0)
            {
                model.AllWidgetProduct = ProductsService.Instance.GetWidgetProductsbyCategory(CategoryID.Value, 4);
            }
            else
            {
                model.AllWidgetProduct = ProductsService.Instance.GetProducts(1, 8);
            }


            return PartialView(model);
        }

        [ChildActionOnly]
        public ActionResult CategoryDropDownWidget()
        {
            HomeViewModel model = new HomeViewModel();
            model.AllCategory = CategoriesService.Instance.allCategory();
            return PartialView("~/Views/Widgets/_CategoryDropDown.cshtml", model);
        }

        [ChildActionOnly]
        public ActionResult SearchingWidget(string searchterm, int? pageNo)
        {
            var pageSize = 3;
            pageNo = pageNo ?? 1;
            HomeViewModel model = new HomeViewModel();
            model.SearchTerm = searchterm;
            model.AllProduct = ProductsService.Instance.FilterProduct(searchterm, pageNo.Value, pageSize);
            var totalProducts = ProductsService.Instance.GetProductCount(searchterm);

            model.Pager = new Pager(totalProducts, pageNo, pageSize);

            return PartialView("~/Views/Widgets/_SearchingWidget.cshtml", model);
        }
        [HttpPost]
        public JsonResult catchproduct(string value)
        {  
            var products=ProductsService.Instance.AutoComSearchTerm(value);
            return Json(products, JsonRequestBehavior.AllowGet);
        }
       
    }
}

Khawla.Web/Views/Shop/FilterProducts.cshtml
@model Khawla.Web.ViewModels.FilterProductsViewModel
@using Khawla.Entities.Code



<div class="row">
    @foreach (var product in Model.Products)
    {


        <div class="shopProduct col-md-3 col-sm-4 col-6">
            <div class="product__item">
                <div class="product__item__pic set-bg" data-setbg="/FileStore/images/@product.ProductPictures.Select(m=>m.Picture.Url).First()" style="background-image:url(/FileStore/images/@product.ProductPictures.Select(m=>m.Picture.Url).First());">
                    <ul class="product__item__pic__hover">
                        <li><a href="#"><i class="fa fa-heart"></i></a></li>
                        <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                        <li><a href="@Url.Action("ShopingCart", "Shop")" data-id="@product.ID" class="productAddToCart"><i class="fa fa-shopping-cart"></i></a></li>
                    </ul>
                </div>
                <div class="product__item__text">
                    <h6><a href="@Url.Action("Details", "Products", new { ID = product.ID })">@product.Name</a></h6>
                    <h5>@product.Price</h5>
                </div>
            </div>
        </div>

    }
</div>
@if (Model.Pager != null && Model.Pager.TotalPages > 1)
{
<div class="product__pagination">
    
        @if (Model.Pager.CurrentPage > 1)
        {
            
                <a data-href="@Url.Action("FilterProducts", "Shop", new { pageNo = Model.Pager.CurrentPage - 1, sortBy = Model.SortBy, categoryID = Model.CategoryID })" class="pageDataLink prev"><i class="fa fa-angle-left"></i></a>
            
        }

        @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
        {
            string activeClass = Model.Pager.CurrentPage == page ? "active" : string.Empty;

            <a data-href="@Url.Action("FilterProducts", "Shop", new { pageNo = page, sortBy = Model.SortBy, categoryID = Model.CategoryID })" title="" class="pageDataLink @activeClass">@page</a>
        }

        @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
        {
            <a data-href="@Url.Action("FilterProducts", "Shop", new { pageNo = Model.Pager.CurrentPage + 1, sortBy = Model.SortBy, categoryID = Model.CategoryID})" class="pageDataLink"><i class="fa fa-angle-right"></i></a>
        }
    <!-- /.flat-pagination -->
</div>
}

    <input type="hidden" id="SearchTerm" value="@Model.SearchTerm" />
    <input type="hidden" id="SortBy" value="@Model.SortBy" />
    <input type="hidden" id="CategoryID" value="@Model.CategoryID" />


<script>
    $(".pageDataLink").click(function () {
        var url = $(this).attr("data-href");
        if (url != "" || url != undefined) {
            GetData(url);
        }
    });
</script>

Khawla.Web/Views/Shop/Index.cshtml
@using Khawla.Entities.Code
@using Khawla.Web.Controllers

@model Khawla.Web.ViewModels.ShopViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var searchinput = Model.SearchTerm != null ? Model.SearchTerm : string.Empty;
}
<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="/Content/img/breadcrumb.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Organi Shop</h2>
                        <div class="breadcrumb__option">
                            <a href="./index.html">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
<!-- Breadcrumb Section End -->
<!-- Product Section Begin -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-5">
                <div class="sidebar">
                    <div class="categorysidebar sidebar__item">
                        <h4 class="widget-title">
                            Products Categories
                        </h4>
                        <ul>
                            @foreach (var category in Model.AllCategory)
                            {
                                <li><a href="@Url.Action("Index", "Shop", new {categoryID=category.ID})">@category.Name</a></li>
                            }


                        </ul>
                    </div>
                    <div class="sidebar__item">
                        <h4>Price</h4>
                        <div class="price-range-wrap">
                            <div class="price-range ui-slider ui-corner-all ui-slider-horizontal ui-widget ui-widget-content"
                                 data-min="@Model.MinimumPrice" data-max="@Model.MaximumPrice">
                                <div class="ui-slider-range ui-corner-all ui-widget-header"></div>
                                <span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"></span>
                                <span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"></span>
                            </div>
                            <div class="range-slider">
                                <div class="price-input">
                                    <input type="text" value="@Model.MinimumPrice " disabled id="minamount" style="float:inline-start">
                                    <input type="text" value="@Model.MaximumPrice " disabled id="maxamount" style="float:right">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="sidebar__item">
                        @{Html.RenderAction("Products", "Widgets", new { isFeatured = false, isLatestProduct = true, topRated = false, topReview = false });}
                    </div>
                </div>
            </div>
            <div class="TotalproductDiv col-lg-9 col-md-7">

                <div class="filter__item">
                    <div class="row">
                        <div class="col-lg-4 col-md-5">
                            <div class="filter__sort">
                                <span>Sort by</span>
                                <select class="ShopSortselect">
                                    <option value="@((int)SortByEnums.Default)">Default</option>
                                    <option value="@((int)SortByEnums.Popularity)">popularity</option>
                                    <option value="@((int)SortByEnums.PriceLowToHigh)">low to high</option>
                                    <option value="@((int)SortByEnums.PriceHighToLow)">high to low</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="filter__found">
                                @if(Model.SearchTerm!=null)
                                {<h6><span>@Model.totalCount </span>Products found for "@searchinput"</h6> }
                                else { <h6><span>@Model.totalCount </span>Products found</h6>}
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-3">
                            <div class="filter__option">
                                <span class="icon_grid-2x2"></span>
                                <span class="icon_ul"></span>
                            </div>
                        </div>

                    </div>
                </div>

                <div id="productsDiv">

                    @{
                        var filterProductsViewModel = new FilterProductsViewModel();
                        filterProductsViewModel.Products = Model.Products;
                        filterProductsViewModel.Pager = Model.Pager;
                        filterProductsViewModel.CategoryID = Model.CategoryID;
                        filterProductsViewModel.SortBy = Model.SortBy;


                        Html.RenderPartial("FilterProducts", filterProductsViewModel);
                    }

                </div>

            </div>
        </div>
    </div>
</section>
<input type="hidden" id="SubCategoryID" value="@Model.SubCategoryID" />
<!-- Product Section End -->
<script>
    $(document).ready(function () {
        // Handler for .ready() called.
        $('html, body').animate({
            scrollTop: $('.TotalproductDiv').offset().top
        }, 'slow');
    });
    //$(".sidebar__item a").click(function (e) {
    //    e.preventDefault();
    //    $('#productsDiv').hide();
    //    $('#productsDiv').load($(this).attr("href")).delay(500).fadeIn('slow');
    ////});
    $(".categorysidebar a").click(function () {
        $("#searchTxt").val('');
        $("#SubCategoryID").val('');
        resetSlider();

    });
    $(".ShopSortselect").change(function() {
        resetSlider();
        $.ajax({

            url: '@Url.Action("FilterProducts", "Shop")',
            data: {

                sortBy: $(".ShopSortselect").val(),
                categoryID: $("#CategoryID").val(),
                subcategoryID: $("#SubCategoryID").val(),
                searchTerm: $("#searchTxt").val(),
            },
            beforeSend: function () {
                $("#productsDiv").hide();

            }

        })
            .done(function (response) {
                @*$("#minamount").val('@Model.MinimumPrice');
                 $("#maxamount").val('@Model.MaximumPrice');*@
                $("#productsDiv").html(response);
                $("#productsDiv").delay(500).fadeIn('slow');


            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });


    });
        var callTimeout;

        var rangeSlider = $(".price-range").slider({


        range: true,
        min: @Model.MinimumPrice,
        max: @Model.MaximumPrice,
        values: [@Model.MinimumPrice,@Model.MaximumPrice],
        slide: function (event, ui) {
            var minamount = ui.values[0];
            var maxamount = ui.values[1];

            $("#minamount").val(minamount + "ট");
            $("#maxamount").val(maxamount + "ট");

            clearTimeout(callTimeout);
            callTimeout = setTimeout(PriceRangeChange, 500);
        }
    });


   
    function GetData(dUrl){
        console.log("getdata in");
        showLoader();
        $.ajax({
                url: dUrl,
                data: {
                    minimumPrice: rangeSlider.slider("values", 0),
                    maximumPrice: rangeSlider.slider("values", 1)
                }
            })
            .done(function (response) {
                console.log("done");
                $("#productsDiv").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                console.log("fail");
                alert("FAIL");
            })
            .always(function(){
                console.log("always");
                hideLoader();
            });
        console.log("getdata out");
    }
    function PriceRangeChange(){
        $.ajax({
                url: '@Url.Action("FilterProducts", "Shop")',
                data: {
                    searchTerm: $("#searchTxt").val(),
                    sortBy: $("#SortBy").val(),
                    categoryID: $("#CategoryID").val(),
                    subcategoryID: $("#SubCategoryID").val(),
                    minimumPrice: rangeSlider.slider("values", 0),
                    maximumPrice: rangeSlider.slider("values", 1),

                }
            })
            .done(function (response) {
                $("#productsDiv").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    }
   /*-------------------
       slide on product query
   ---------------------    */
      @*function resetSlider() {
          var $slider = $(".price-range");
          $slider.slider("values", 0, @Model.MinimumPrice);
          $slider.slider("values", 1, @Model.MaximumPrice);
          $("#minamount").val('@Model.MinimumPrice');
          $("#maxamount").val('@Model.MaximumPrice');
      }*@
</script>