Khawla.Web/ViewModels/CategoriesViewModel.cs
using Khawla.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Khawla.Web.ViewModels
{
    public class CategoryCreateViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsFeatured { get; set; }
        public string CategoryPictures { get; set; }
        public List<CategoryPicture> CategoryPictureList { get; set; }

        
    }
    public class CategoryListingViewModel
    {
        public List<Category> Allcategories { get; set; }
        public string SearchTerm { get; set; }
        public Pager Pager { get; set; }
    }
    public class EditCategoryViewModel
    {
        public int Id { get; set; }
        public Category category { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsFeatured { get; set; }
        public string CategoryPictures { get; set; }
        
    }
}

Khawla.Web/Controllers/CategoriesController.cs
using Khawla.Entities;
using Khawla.Web.ViewModels;
using System.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Khawla.Service;

namespace Khawla.Web.Controllers
{
    public class CategoriesController : Controller
    {
        // GET: Categories
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult CategoryList(string search,int? pageNo)
        {
            var pageSize = 3;
            pageNo = pageNo ?? 1;

            CategoryListingViewModel model = new CategoryListingViewModel();

            model.SearchTerm = search;
            model.Allcategories = CategoriesService.Instance.FilterCategories(search,pageNo.Value,pageSize);

            var TotalCategory = CategoriesService.Instance.TotalCategoryCount(search);

            model.Pager = new Pager(TotalCategory, pageNo, pageSize);

            return PartialView(model);
        }
        public ActionResult Create()
        {
            
            return PartialView();
        }
        [HttpPost]
        public JsonResult Create(CategoryCreateViewModel model)
        {
            JsonResult result = new JsonResult();
            if (ModelState.IsValid)
            {
                var newCategory = new Category();

                newCategory.Name = model.Name;
                newCategory.Description = model.Description;
                newCategory.IsFeatured = model.IsFeatured;
                if (!string.IsNullOrEmpty(model.CategoryPictures))
                {
                    var pictureId = model.CategoryPictures
                        .Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                        .Select(int.Parse).ToList();
                    newCategory.CategoryPictures = new List<CategoryPicture>();
                    newCategory.CategoryPictures.AddRange(pictureId.Select(s => new CategoryPicture()
                    { CategoryId = newCategory.ID, PictureId = s }).ToList());
                }
                CategoriesService.Instance.SaveCategory(newCategory);

                    result.Data = new { success = true };
                }
                else
                {
                    result.Data = new { success = false, message = "Invalid Inputs" };
                }
                return result;
            }

        public ActionResult Edit(int Id)
        {
            EditCategoryViewModel model = new EditCategoryViewModel();
            model.category = CategoriesService.Instance.categoryById(Id);

            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(EditCategoryViewModel model)
        {
            var category = CategoriesService.Instance.categoryById(model.Id);

            category.ID = model.Id;
            category.Name = model.Name;
            category.Description = model.Description;
            category.IsFeatured = model.IsFeatured;
            if (!string.IsNullOrEmpty(model.CategoryPictures))
            {
                var pictureId = model.CategoryPictures
                      .Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                      .Select(int.Parse).ToList();
                category.CategoryPictures = new List<CategoryPicture>();
                category.CategoryPictures.AddRange(pictureId.Select(s => new CategoryPicture()
                { CategoryId = category.ID, PictureId = s }).ToList());
            }
            CategoriesService.Instance.UpdateCategory(category);

            return RedirectToAction("CategoryList");
        }
        public ActionResult Delete(int Id)
        {
            CategoriesService.Instance.DeleteCategory(Id);

            return RedirectToAction("CategoryList");
        }
    }
}

Khawla.Web/Controllers/SharedController.cs
using Khawla.Entities;
using Khawla.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Khawla.Web.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        [HttpPost]
        public JsonResult UploadPictures()
        {
            JsonResult json = new JsonResult();
            var picturesJson = new List<object>();
            var pictures = Request.Files;

            for(int i = 0; i < pictures.Count; i++)
            {
                var picture = pictures[i];
                var fileName = Guid.NewGuid() + Path.GetExtension(picture.FileName);
                var path = Server.MapPath("~/FileStore/images/") + fileName;

                //var picUrl= "~FileStore/images/"+fileName;

                picture.SaveAs(path);//into project images folder

                //into database

                var newPic = new Picture();
                newPic.Url = fileName;
                int picId = SharedService.Instance.SavePicture(newPic);

                picturesJson.Add(new { id = picId, url = fileName});

            }

            json.Data = picturesJson;


            return json;
        }
    }
}

Khawla.Web/Views/Categories/CategoryList.cshtml
@model Khawla.Web.ViewModels.CategoryListingViewModel

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-12">
                <h1>Category</h1>
                <hr />
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <form>
                    <input type="text" id="searchTxt" name="search" class="form-control mr-1" placeholder="Search by Name..." value="@Model.SearchTerm">
                    <br />
                    <div class="input-group-append link-danger" id="button-addon4">
                        <button id="searchBtn" class="btn btn-primary mr-1" type="button">Search</button>
                        <button id="resetBtn" class="btn btn-secondary mr-1" type="button">Reset</button>
                        <button id="CreateCategoryBtn" class="btn btn-info" type="button">Create New Category</button>
                    </div>
                </form>
            </div>
        </div>
        <br />
        <div id="CategoryListing">

            <table class="table table-striped">
                <thead style="background-color:darkseagreen">
                    <tr>
                        <td>Id</td>

                        <td>Name</td>

                        <td>Description</td>

                        <td>Actions</td>
                    </tr>

                </thead>
                <tbody>
                    @if (Model.Allcategories != null && Model.Allcategories.Count > 0)
                    {
                        int i = 1;
                        foreach (var category in Model.Allcategories)
                        {
                            <tr>
                                <td>@i</td>

                                <td>@category.Name</td>

                                <td>@category.Description</td>

                                <td>
                                    <button type="button" class="DeleteBtn btn btn-danger" data-id="@category.ID">Delete</button>


                                    <button type="button" class="EditBtn btn btn-primary" data-id="@category.ID" data-toggle="modal" data-target="FormModel">Edit</button>
                                </td>


                            </tr>
                            i++;
                        }

                    }
                    else
                    {
                        <tr>
                            <td colspan="12" class="text-center alert alert-danger">
                                No Category found!!!.
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            @if (Model.Pager != null && Model.Pager.TotalPages > 1)
            {<nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        @if (Model.Pager.CurrentPage == 1)
                        {
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">First</a>
                            </li>
                        }
                        else
                        {
                            <li class="page-item">
                                <a class="pageDataLink page-link text-primary" data-href="@Url.Action("CategoryList","Categories" ,new {search=Model.SearchTerm,pageNo=Model.Pager.CurrentPage-1})" style="cursor:pointer">Previous</a>
                            </li>
                        }
                        @for (int page = Model.Pager.StartPage; page < Model.Pager.EndPage; page++)
                        {
                            var acitve = page == Model.Pager.CurrentPage ? "active bg-info" : string.Empty;
                            <li class="page-item @acitve">
                                <a class="pageDataLink page-link text-primary" data-href="@Url.Action("CategoryList","Categories" ,new {search=Model.SearchTerm,pageNo=page})" style="cursor:pointer">@page</a>
                            </li>
                        }
                        @if (Model.Pager.CurrentPage == Model.Pager.EndPage)
                        {
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Last</a>
                            </li>
                        }
                        else
                        {
                            <li class="page-item bg-white">
                                <a class="pageDataLink page-link text-primary" data-href="@Url.Action("CategoryList","Categories" ,new {search=Model.SearchTerm,pageNo=Model.Pager.CurrentPage+1})" style="cursor:pointer">Next</a>
                            </li>
                        }
                    </ul>
                </nav>}


        </div>



    </div>

</div>

<div id="picTemplate" style="display:none">
    <img src="" class="image img-thumbnail mt-2"style="width:200px;height:200px" data-id="" />
</div>

<script>

    $("#CreateCategoryBtn").click(function () {
        $.ajax({
            type: "get",
            url: '@Url.Action("Create","Categories")',
        })
            .done(function (response) {
                $("#FormModel").modal("toggle");
                $("#contentArea").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });

    function AttachNewImage(imgId, imgUrl)
    {
        var imgHtml = $("#picTemplate").clone();

        imgHtml.find(".image").attr("data-id", imgId);
        imgHtml.find(".image").attr("src", "/FileStore/images/" + imgUrl);
        $("#picArea").append(imgHtml.html());
        RemoveImageonClick();


    }
    function RemoveImageonClick() {
        $("#picArea .image").click(function () {
            $(this).remove();
            $("#uploadCategoryPic").val("");
            $("#picLength").show();
            $("#picLength").append($("#picArea .image").length + " picture. ");
            $("#errorDiv").hide()
        })
    }
    $("#cancelBtn").click(function () {
        $("#contentArea").html("");
        focusAction("tableContainer");
    });


    $("#searchBtn").click(function () {
        $.ajax({
            url: '@Url.Action("CategoryList", "Categories")',
            data: {

                search: $("#searchTxt").val()
            }

        })
            .done(function (response) {

                $("#tableContainer").html(response);


            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });


    });
    $("#resetBtn").click(function () {
        $.ajax({
            url: '@Url.Action("CategoryList", "Categories")',
            data: {

                search: "",
            }

        })
            .done(function (response) {

                $("#tableContainer").html(response);


            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });


    });
     $(".EditBtn").click(function () {
        $.ajax({
            type: "GET",
            url: "@Url.Action("Edit", "Categories")",
            data: { Id: $(this).attr('data-id') }

        })
            .done(function (response) {

                $('#FormModel').modal('toggle');
                $("#contentArea").html(response);

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });


     });
    $(".DeleteBtn").click(function () {
        swal({
            title: "Confirm?",
            text: "Are you sure you want to delete this Category?",
            icon: "warning",
            buttons: true,
            dangerMode: true
        })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: "Post",
                        url: "@Url.Action("Delete", "Categories")",
                        data: {
                            
                            Id: $(this).attr('data-id'),
                        }
                    })
                        .done(function (response) {

                            $("#tableContainer").html(response);
                            focusAction("contentArea");
                        })
                        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                            alert("FAIL");
                        });
                }
            });
    });
    $(".pageDataLink").click(function () {

        var url = $(this).attr("data-href");

        $.ajax({

            url: url

        })
            .done(function (response) {


                $("#tableContainer").html(response);


            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });


    });

    function ReloadTable() {
        $.ajax({

            url:'@Url.Action("CategoryList","Categories")',
            method:'GET',

        })
           .done(function (response) {


               $("#tableContainer").html(response);


           })
           .fail(function (XMLHttpRequest, textStatus, errorThrown) {
               alert("FAIL");
           });

    }

    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContainer");
    });
</script>

Khawla.Web/Views/Categories/Create.cshtml
<div class="modal-header">
    <h1 class="modal-title"> Category Create Form</h1>
</div>

<form id="CategoryCreateTable" style="overflow: auto">
    <div class="modal-body">
        <div class=" form-group">
            <label for="Name">Name</label>
            <input id="name" type="text" name="Name" class="form-control" />
        </div>
        <div class=" form-group">
            <label for="Name">Is Featured ?</label>
            <input name="IsFeatured" type="radio" value="True" />True
            <input name="IsFeatured" type="radio" value="False" />False
        </div>
        <div class=" form-group">
            <label for="Name">Description</label>
            <input id="description" type="text" name="Description" class="form-control" />
        </div>
        <div class=" form-group">
            <label for="CategoryPictures" class="btn btn-warning" style="cursor:pointer">Add Picture</label>
            <span id="picLength" class="badge badge-warning p-1"></span>
            <input id="uploadCategoryPic" type="file" name="CategoryPictures" class="form-control" accept=".png,.jpg" />
            <input type="hidden" id="pictureId" name="CategoryPictures" />
            <div id="picArea"></div>
        </div>
    </div>
    <div id="errorDiv"class="form-group alert alert-danger" style="display:none">

    </div>
    <div class="modal-footer">
        <button id="cancelBtn" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button id="CategorySaveBtn" type="button" class="btn btn-primary">Save changes</button>
    </div>
</form>

<script>
    $("#CategoryCreateTable").validate({
        rules: {
            Name: {
                required: true,
                minlength: 3,
                maxlength: 150
            },
            Description: {
                required: true,
                minlength: 5,
                maxlength: 700,
            },
            CategoryPictures: {
                required: true,

            }
        },
        messages: {
            Title: {
                required: "Name is rquired.",
                minlength: "Minmum length is 15",
                maxlength: "Maximum length is 150"
            },
            Description: {
                required: "Description is rquired.",
                minlength: "Minmum length is 5",
                maxlength: "Maximum length is 700"
            },
            CategoryPictures: {
                required: "This page needs an image",

            },
        },
        errorClass: "text-danger"
    })

    $("#uploadCategoryPic").change(function () {

        var picture = this.files;
        var picsLength = picture.length;
        var picsData = new FormData();
        for (var i = 0; i < picsLength; i++) {
            picsData.append("picture", picture[i]);
        }
        var allpic = $("#picArea > img").length;

        if (allpic<=0) {

            $.ajax({
                type: "post",
                url: '@Url.Action("UploadPictures", "Shared")',
                data: picsData,
                dataType: "json",
                processData: false,
                contentType: false
            })
                .done(function (response) {
                    for (var i = 0; i < response.length; i++) {
                        var picResponse = response[i];
                        AttachNewImage(picResponse.id, picResponse.url);
                    }

                    var count = $("#picArea > img").length;
                    $("#picLength").empty();
                    $("#picLength").append(count + " pictures. ");
                    $("#piclength").show();

                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("FAIL");
                });
        }
        else {
            $("#errorDiv").html(" 1 Picture for category!");
            $("#errorDiv").show();
        }
    });

    $("#CategorySaveBtn").click(function () {
        if ($("#CategoryCreateTable").valid())
        {
            var picIds = [];
            $("#picArea .image").each(function () {
                var picId = $(this).attr("data-id");
                picIds.push(picId);
            });
            $("#pictureId").val(picIds);

            $.ajax({
                type: 'post',
                url: '@Url.Action("Create","Categories")',
                data: $("#CategoryCreateTable").serialize(),
            })
                .done(function (response) {
                    if (response.success) {
                        ReloadTable()
                        $("#FormModel").modal('hide');
                    }
                    else {
                        $("#errorDiv").html(response.message);
                        $("#errorDiv").show();
                    }
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("FAIL");
                });
        }
    })
</script>

Khawla.Web/Views/Categories/Edit.cshtml
@model Khawla.Web.ViewModels.EditCategoryViewModel

@{ 
    var trueChecked = Model.category.IsFeatured ? "checked" : string.Empty;
    var falseChecked = !Model.category.IsFeatured ? "checked" : string.Empty;
}
<div class="modal-header">
    <h5 class="modal-title">Edit Category</h5>
</div>
<form id="UpdateTable" style="overflow: auto">
    <div class="modal-body">
        <input type="hidden" name="ID" value="@Model.category.ID" />
        <div class="form-group">
            <label>Name</label>
            <input class="form-control" name="Name" value="@Model.category.Name" />
        </div>
        <div class="form-group">
            <label>Description</label>
            <input class="form-control" name="Description" value="@Model.category.Description" />
        </div>
        <div class=" form-group">
            <label for="Name">Is Featured ?</label>
            <input name="IsFeatured" type="radio" value="True"@trueChecked />True
            <input name="IsFeatured" type="radio" value="False"@falseChecked />False
        </div>
        <div class="form-group">
            <label for="uploadCategoryPic" class="btn btn-warning" style="cursor:pointer">
                Update Pictures
                @if (Model.category.CategoryPictures != null && Model.category.CategoryPictures.Count() > 0)
                {
                    <span id="existPicLength" class="badge badge-warning p-1">@Model.category.CategoryPictures.Count() Pictures.</span>
                }
                <span id="picLength" class="badge badge-warning p-1" style="display:none"></span>
            </label>
            <input id="uploadCategoryPic" class="form-control" name="CategoryPictures" type="file" style="display:none" />
            <input type="hidden" id="pictureId" name="CategoryPictures" />
            <div id="picArea">
                @if (Model.category.CategoryPictures != null && Model.category.CategoryPictures.Count > 0)
                {
                    foreach (var picture in Model.category.CategoryPictures)
                    {
                        <img src="~/FileStore/images/@picture.Picture.Url" style="width:200px;height:200px" class="image img-thumbnail mt-2" data-id="@picture.PictureId" />
                    }
                }
            </div>

        </div>


        <div class="modal-footer">
            <button type="button" id="UpdateBtn" class="btn btn-success">Update</button>
            <button type="button" id="cancelBtn" class="btn btn-warning" data-dismiss="modal">Cancel</button>
        </div>
    </div>
</form>
<script>
        RemoveImageonClick()
        
     $("#UpdateBtn").click(function () {

        var picIds = [];

        $("#picArea .image").each(function () {
            var picId = $(this).attr("data-id");

            picIds.push(picId);
        });

        $("#pictureId").val(picIds);
        $.ajax({

            type: 'POST',
            url: '@Url.Action("Edit", "Categories")',
            data: $("#UpdateTable").serialize()

        })
            .done(function (response) {

                $("#tableContainer").html(response);
                $('#FormModel').modal('hide');
                //$("#contentArea").html('');

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });


     });
    $("#uploadCategoryPic").change(function () {

        var picture = this.files;
        var picsLength = picture.length;
        var picsData = new FormData();
        for (var i = 0; i < picsLength; i++) {
            picsData.append("picture", picture[i]);
        }
        var allpic = $("#picArea > img").length;

        if (allpic<=0) {

            $.ajax({
                type: "post",
                url: '@Url.Action("UploadPictures", "Shared")',
                data: picsData,
                dataType: "json",
                processData: false,
                contentType: false
            })
                .done(function (response) {
                    for (var i = 0; i < response.length; i++) {
                        var picResponse = response[i];
                        AttachNewImage(picResponse.id, picResponse.url);
                    }

                    var count = $("#picArea > img").length;
                    $("#picLength").empty();
                    $("#picLength").append(count + " pictures. ");
                    $("#piclength").show();

                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("FAIL");
                });
        }
        else {
            $("#errorDiv").html(" 1 Picture for category!");
            $("#errorDiv").show();
        }
    });
</script>

Khawla.Web/Views/Categories/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/Content/bootstrap.min.css" type="text/css">
<div>
    <div id="tableContainer">
        @{
            Html.RenderAction("CategoryList");
        }
    </div>

    <hr />
    @*<div id="contentArea">
        </div>*@
    <div class="modal fade" id="FormModel" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content" id="contentArea">
            </div>
        </div>
    </div>



</div>