Khawla.Web/ViewModels/ProductsViewModel.cs
using Khawla.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Khawla.Web.ViewModels
{
    public class ProductsCreateViewModel
    {
        public string Name { get; set; }

        public string Description { get; set; }
        public string Summery { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }

        public int CategoryId { get; set; }
        public  Category Category { get; set; }
        public List<ProductPicture> ProductPictureList { get; set; }
        public string ProductPictures { get; set; }
        public List<Category> Categories { get; set; }
        public int SubCategoryId { get; set; }
        public List<SubCategory> SubCategories { get; set; }
        public int Id { get; set; }
        public Product Product { get; set; }
    }
    public class ProductListingViewModel
    {
        public int? CategoryId { get; set; }
        public string SearchTerm { get; set; }
        public List<ProductPicture> ProductPictures { get; set; }
        public List<Category> AllCategory { get; set; }
        public List<Product> AllProduct { get; set; }
        
        public Pager Pager { get; set; }
    }
    public class ProductDetalisViewModel
    {
        public Product Product { get; set; }
        
    }

}

Khawla.Web/Controllers/ProductsController.cs
using Khawla.Entities;
using Khawla.Service;
using Khawla.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Khawla.Web.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult ProductList(int? categoryId, string search, int? pageNo )
        {
            var pageSize = 3;
            pageNo = pageNo ?? 1;

            ProductListingViewModel model = new ProductListingViewModel();
            //model.PageNo= pageNo ?? 1;
            model.CategoryId = categoryId;
            model.SearchTerm = search;
            
            model.AllProduct = ProductsService.Instance.FilterProduct(categoryId, search, pageNo.Value, pageSize);
            model.AllCategory = CategoriesService.Instance.allCategory();
            var totalProducts = ProductsService.Instance.GetProductCount(categoryId, search);

            model.Pager = new Pager(totalProducts, pageNo, pageSize);

            return PartialView(model);
        }

        public ActionResult Create()
        {
            ProductsCreateViewModel model = new ProductsCreateViewModel();
            model.Categories = CategoriesService.Instance.allCategory();
            model.SubCategories = SubCategoriesService.Instance.allSubCategory();
            return PartialView(model);
        }
        [HttpPost]
        public JsonResult Create(ProductsCreateViewModel model)
        {
            JsonResult result = new JsonResult();
            if (ModelState.IsValid)
            {
                var newProduct = new Product();

                newProduct.Name = model.Name;
                newProduct.Description = model.Description;
                newProduct.Summery = model.Summery;
                newProduct.Price = model.Price;
                newProduct.Quantity = model.Quantity;
                newProduct.CategoryId = model.CategoryId;
                newProduct.SubCategoryId = model.SubCategoryId;

                if (!string.IsNullOrEmpty(model.ProductPictures))
                {
                    var pictureId = model.ProductPictures
                        .Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                        .Select(int.Parse).ToList();
                    newProduct.ProductPictures = new List<ProductPicture>();
                    newProduct.ProductPictures.AddRange(pictureId.Select(s => new ProductPicture()
                    { ProductId = newProduct.ID, PictureId = s }).ToList());
                }
                ProductsService.Instance.SaveProduct(newProduct);

                result.Data = new { success = true };
            }
            else
            {
                result.Data = new { success = false, message = "Invalid Inputs" };
            }
            return result;
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            ProductsCreateViewModel model = new ProductsCreateViewModel();

            model.Product = ProductsService.Instance.GetProductById(Id);
            model.Categories = CategoriesService.Instance.allCategory();


            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(ProductsCreateViewModel model)
        {
            
            var Product = ProductsService.Instance.GetProductById(model.Id);
            Product.Name = model.Name;
            Product.Summery = model.Summery;
            Product.Description = model.Description;
            Product.Price = model.Price;
            Product.Quantity = model.Quantity;
            Product.CategoryId = model.CategoryId;


            if (!string.IsNullOrEmpty(model.ProductPictures))
            {
                var pictureIds = model.ProductPictures.Split(',').Select(int.Parse);
                Product.ProductPictures = new List<ProductPicture>();
                Product.ProductPictures.AddRange(pictureIds.Select(x => new ProductPicture() { ProductId = Product.ID, PictureId = x }).ToList());

            }



            ProductsService.Instance.UpdateProduct(Product);

            return RedirectToAction("ProductList");
        }

        [HttpGet]
        public ActionResult Details(int Id)
        {
            ProductDetalisViewModel model = new ProductDetalisViewModel();

            model.Product = ProductsService.Instance.GetProductById(Id);
            


            return View(model);
        }
        [HttpPost]
        public ActionResult Delete(int Id)
        {

            ProductsService.Instance.Deleteproduct(Id);
            return RedirectToAction("ProductList");
        }

    }
}

Khawla.Web/Controllers/SharedController.cs
using Khawla.Entities;
using Khawla.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Khawla.Web.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        [HttpPost]
        public JsonResult UploadPictures()
        {
            JsonResult json = new JsonResult();
            var picturesJson = new List<object>();
            var pictures = Request.Files;

            for(int i = 0; i < pictures.Count; i++)
            {
                var picture = pictures[i];
                var fileName = Guid.NewGuid() + Path.GetExtension(picture.FileName);
                var path = Server.MapPath("~/FileStore/images/") + fileName;

                //var picUrl= "~FileStore/images/"+fileName;

                picture.SaveAs(path);//into project images folder

                //into database

                var newPic = new Picture();
                newPic.Url = fileName;
                int picId = SharedService.Instance.SavePicture(newPic);

                picturesJson.Add(new { id = picId, url = fileName});

            }

            json.Data = picturesJson;


            return json;
        }
    }
}

Khawla.Web/Controllers/SubCategoriesController.cs
using Khawla.Entities;
using Khawla.Service;
using Khawla.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Khawla.Web.Controllers
{
    public class SubCategoriesController : Controller
    {
        // GET: SubCategories
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult SubCategoryList(string search, int? pageNo)
        {
            var pageSize = 3;
            pageNo = pageNo ?? 1;

            SubCategoryListingViewModel model = new SubCategoryListingViewModel();

            model.SearchTerm = search;
            model.Allsubcategories = SubCategoriesService.Instance.FilterSubCategories(search, pageNo.Value, pageSize);

            var TotalCategory = CategoriesService.Instance.TotalCategoryCount(search);

            model.Pager = new Pager(TotalCategory, pageNo, pageSize);

            return PartialView(model);
        }
        public ActionResult Create()
        {
            SubCategoryCreateViewModel model = new SubCategoryCreateViewModel();
            model.AllCategory = CategoriesService.Instance.allCategory();
            return PartialView(model);
        }
        [HttpPost]
        public JsonResult Create(SubCategoryCreateViewModel model)
        {
            JsonResult result = new JsonResult();
            if (ModelState.IsValid)
            {
                var newSubCategory = new SubCategory();

                newSubCategory.SubCategoryName = model.Name;
                newSubCategory.CategoryID = model.CategoryId;
                
                SubCategoriesService.Instance.SaveSubCategory(newSubCategory);

                result.Data = new { success = true };
            }
            else
            {
                result.Data = new { success = false, message = "Invalid Inputs" };
            }
            return result;
        }

        public ActionResult Edit(int Id)
        {
            SubCategoryCreateViewModel model = new SubCategoryCreateViewModel();
            model.subCategory = SubCategoriesService.Instance.SubCategoryById(Id);

            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(SubCategoryCreateViewModel model)
        {
            var subcategory = SubCategoriesService.Instance.SubCategoryById(model.Id);

            subcategory.Id = model.Id;
            subcategory.SubCategoryName = model.Name;

            SubCategoriesService.Instance.UpdateSubCategory(subcategory);

            return RedirectToAction("SubCategoryList");
        }
        public ActionResult Delete(int Id)
        {
            SubCategoriesService.Instance.DeleteSubCategory(Id);

            return RedirectToAction("SubCategoryList");
        }

        public JsonResult SubcategoryByCategoryId(int? CategoryId)
        {
            var subcategories = SubCategoriesService.Instance.GetSubCategoryByCategoryId((int)CategoryId);
            return Json(subcategories, JsonRequestBehavior.AllowGet);
        }
    }
}

Khawla.Web/Views/Products/Create.cshtml
@model Khawla.Web.ViewModels.ProductsCreateViewModel
<div class="modal-header">
    <h5 class="modal-Name">Add Product</h5>
</div>
<form id="CreateTable" style="overflow: auto">
    <div class="modal-body">


        <div class="form-group">
            <label for="Name">Name</label>
            <input type="text" class="form-control" name="Name" id="Name" value="@Model.Name" />
        </div>

        <div class="form-group">
            <label for="">Category</label>
            <select class="form-group"id="categoryId" name="CategoryId">
                <option value="">Select Category</option>
                @foreach (var category in Model.Categories)
                {
                    <option value="@category.ID">@category.Name</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="">Sub-Category</label>
            <div class="col-md-10">
                <select class="form-control" id="subcategoryId" name="subcategoryId">
                    <option>Select Sub-Category</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="Summery">Summery</label>
            <input type="text" class="form-control" name="Summery" id="Summery" value="@Model.Summery" />
        </div>

        <div class="form-group">
            <label for="Description">Description</label>
            <input type="text" class="form-control" name="Description" id="Description" value="@Model.Description" />
        </div>
        <div class="form-group">
            <label for="Quantity">Quantity</label>
            <input type="text" class="form-control" name="Quantity" id="Quantity" value="@Model.Quantity" />
        </div>
        <div class="form-group">
            <label for="Price">Price</label>
            <input class="form-control" name="Price" id="Price" value="@Model.Price" />
        </div>
        <div class="form-group">
            <label for="uploadProductPic" class="btn btn-warning" style="cursor:pointer">
                Add Pictures
                <span id="picLength" class="badge badge-warning p-1" style="display:none"></span>
            </label>

            <input id="uploadProductPic" class="form-control" name="ProductPictures" type="file" style="display:none" multiple="multiple" />
            <input type="hidden" id="pictureIds" name="ProductPictures" />
            <div id="picsArea"></div>
        </div>
        <div id="errorDiv" class="form-group alert alert-danger" style="display:none">

        </div>
    </div>
    <div class="modal-footer">
        <button type="button" id="cancelBtn" class="btn btn-warning" data-dismiss="modal">Cancel</button>
        <button id="ProductSaveBtn" type="button" class="btn btn-primary">Save changes</button>
    </div>
</form>

<script>
    
    $("#categoryId").change(function () {
             var categoryId = $("#categoryId").val();
            $("#subcategoryId").empty();
            $("#subcategoryId").append('<option>--Select Sub-Category--</option>');
           
            $.ajax({
                type: "Get",
                url: '@Url.Action("SubcategoryByCategoryId", "SubCategories")',
                contentType: "application/json; charset=utf-8",
                data: { CategoryId: categoryId },
                dataType: "json",
                success: function (data) {
                    
                    $.each(data, function (key, value) {

                        $("#subcategoryId").append('<option value=' + value.Id + '>' + value.SubCategoryName + '</option>');
                    });
                },
            });
        });
    


    $("#CreateTable").validate({
        rules: {
            Name: {
                required: true,
                minlength: 3,
                maxlength: 150
            },
            Summery: {
                required: true,
                minlength: 10,
                maxlength: 50
            }
        },
        messages: {
            Name: {
                required: "Name is rquired.",
                minlength: "Minmum length is 15",
                maxlength: "Maximum length is 150"
            },
            Summery: {
                required: "Summery is rquired.",
                minlength: "Minmum length is 10",
                maxlength: "Maximum length is 150"
            }
        },
        errorClass: "text-danger"
    })
    $("#ProductSaveBtn").click(function () {
        if ($("#CreateTable").valid()) {
            var picIds = [];
            $("#picsArea .image").each(function () {
                var picId = $(this).attr("data-id");
                picIds.push(picId);
            });
            $("#pictureIds").val(picIds);
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Create", "Products")',
                data: $('#CreateTable').serialize(),
            })
            .done(function (response) {
                if (response.success) {
                    ReloadTable()
                    $("#FormModel").modal('hide');
                }
                else {
                    $("#errorDiv").html(response.message);
                    $("#errorDiv").show();
                }
                //$("#tableContainer").html(response);
                //$('#FormModel').modal('hide');
                //$("#contentArea").html('');
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
        }
    });
    $("#uploadProductPic").change(function () {
        var pictures = this.files;
        var picsLength = pictures.length;
        if (picsLength > 5) {
            alert("Please,Upload 5 Photo not more than that!");
            picsLength = 5;
        }
        var picsData = new FormData();
        for (var i = 0; i < picsLength; i++) {
            picsData.append("picture", pictures[i]);
        }
        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadPictures", "Shared")',
            data: picsData,
            dataType: "json",
            processData: false,
            contentType: false
        })
            .done(function (responses) {
                for (var i = 0; i < responses.length; i++) {
                    var picResponse = responses[i];
                    AttachNewImage(picResponse.id, picResponse.url);
                }
                var oldLength;
                var newLength;
                if ($("#picLength").text()) {
                    oldLength = $("#picLength").text()[0];
                    newLength = parseFloat(oldLength) + parseFloat(picsLength);
                    $("picLength").empty();
                }
                else {
                    newLength = picsLength;
                }
                $("#picLength").empty();
                $("#picLength").append(newLength + " pictures. ");
                $("#piclength").show();
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
</script>

Khawla.Web/Views/Products/Edit.cshtml
@model Khawla.Web.ViewModels.ProductsCreateViewModel
<div class="modal-header">
    <h5 class="modal-Name">Edit Product</h5>
</div>
<form id="UpdateTable" style="overflow: auto">
    <div class="modal-body">
        <input type="hidden" name="Id" value="@Model.Product.ID" />
        <div class="form-group">
            <label>Name</label>
            <input class="form-control" name="Name" value="@Model.Product.Name" />
        </div>

        <div class="form-group">
            <label for="Category">Category</label>
            <select class="form-group" name="CategoryId">
                @foreach (var category in Model.Categories)
                {
                    var selected = category.ID == Model.Product.CategoryId ? "selected" : string.Empty;
                    <option @selected value="@category.ID">@category.Name</option>
                }


            </select>
        </div>
        <div class="form-group">
            <label>Summery</label>
            <input class="form-control" name="Summery" value="@Model.Product.Summery" />
        </div>
        <div class="form-group">
            <label>Description</label>
            <input class="form-control" name="Description" value="@Model.Product.Description" />
        </div>
        <div class="form-group">
            <label>Quantity</label>
            <input class="form-control" name="Quantity" value="@Model.Product.Quantity" />
        </div>
        <div class="form-group">
            <label>Price</label>
            <input class="form-control" name="Price" value="@Model.Product.Price" />
        </div>
        
        <div class="form-group">
            <label for="uploadProductPic" class="btn btn-warning" style="cursor:pointer">
                Update Pictures
                @if (Model.ProductPictures != null && Model.ProductPictures.Count() > 0)
                {
                    <span id="existPicLength" class="badge badge-warning p-1">@Model.ProductPictures.Count() Pictures.</span>
                }
                <span id="picLength" class="badge badge-warning p-1" style="display:none"></span>
            </label>
            <input id="uploadProductPic" class="form-control" name="ProductPictures" type="file" style="display:none" multiple="multiple" />
            <input type="hidden" id="pictureIds" name="ProductPictures" />
            <div id="picsArea">
                @if (Model.Product.ProductPictures != null && Model.Product.ProductPictures.Count > 0)
                {
                    foreach (var picture in Model.Product.ProductPictures)
                    {
                        <img src="~/FileStore/images/@picture.Picture.Url"style="width:200px;height:200px"v class="image img-thumbnail mt-2" data-id="@picture.PictureId" />
                    }
                }
            </div>

        </div>


        <div class="modal-footer">
            <button type="button" id="UpdateBtn" class="btn btn-success">Update</button>
            <button type="button" id="cancelBtn" class="btn btn-warning" data-dismiss="modal">Cancel</button>
        </div>
    </div>
</form>

    <script>
    RemoveImageOnClick();
    
    $("#UpdateBtn").click(function () {

        var picIds = [];

        $("#picsArea .image").each(function () {
            var picId = $(this).attr("data-id");

            picIds.push(picId);
        });

        $("#pictureIds").val(picIds);
        $.ajax({

            type: 'POST',
            url: '@Url.Action("Edit", "Products")',
            data: $("#UpdateTable").serialize()

        })
            .done(function (response) {

                $("#tableContainer").html(response);
                $('#FormModel').modal('hide');
                //$("#contentArea").html('');

            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });


    });
    $("#uploadProductPic").change(function () {
        var pictures = this.files;
        var picsLength = pictures.length;
        if (picsLength > 5) {
            alert("Please,Upload 5 Photo not more than that!");
            picsLength = 5;
        }
        var picsData = new FormData();
        for (var i = 0; i < picsLength; i++) {
            picsData.append("picture", pictures[i]);
        }
        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadPictures", "Shared")',
            data: picsData,
            dataType: "json",
            processData: false,
            contentType: false
        })
            .done(function (responses) {



                for (var i = 0; i < responses.length; i++) {
                    var picResponse = responses[i];
                    AttachNewImage(picResponse.id, picResponse.url);

                }
                var count = $("#picsArea > img").length;
                $("#picLength").empty();
                $("#picLength").append(count + " pictures. ");
                $("#piclength").show();
               
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContainer");
    });

    </script>

Khawla.Web/Views/Products/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/Content/bootstrap.min.css" type="text/css">
<div>
    <div id="tableContainer">
        @{
            Html.RenderAction("ProductList");
        }
    </div>

    <hr />
    
    <div class="modal fade" id="FormModel" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content" id="contentArea">
            </div>
        </div>
    </div>



</div>